---
title: "Untitled"
author: "Brenda Corina Cerezo Silva"
date: "5/4/2021"
output:
  word_document: default
  pdf_document: default
---

La función del coeficiente:

```{r, echo=TRUE,eval=TRUE,attr.source='.numberLines'}
rhot <- function(a,b,c,d){
  set.seed(2021)
  a = ifelse(a==0,0.5,a)
  b = ifelse(b==0,0.5,b)
  c = ifelse(c==0,0.5,c)
  d = ifelse(d==0,0.5,d)
  N = a+b+c+d
  h = qnorm(0.5 + ((a+c)-(b+d))/(2*N))
  k = qnorm(0.5 + ((a+b)-(c+d))/(2*N))
  H = (1/sqrt(2*pi))*exp(-0.5*h^2)
  K = (1/sqrt(2*pi))*exp(-0.5*k^2)
  peh <- qnorm(3/4)/(H*sqrt(N))*sqrt((b+d)*(a+c)/(N^2))
  pek <- qnorm(3/4)/(K*sqrt(N))*sqrt((c+d)*(a+b)/(N^2))
  eps = (a*d-b*c)/(N*N*H*K)
  coef1 = 1
  coef2 = h*k/factorial(2)
  coef3 = (h^2-1)*(k^2-1)/factorial(3)
  coef4 = h*(h^2-3)*k*(k^2-3)/factorial(4)
  coef5 = (h^4-6*h^2+3)*(k^4-6*k^2+3)/factorial(5)
  coef6 = h*(h^4-10*h^2+15)*k*(k^4-10*k^2+15)/factorial(6)
  coef7 = (h^6-15*h^4+45*h^2-15)*(k^6-15*k^4+45*k^2-15)/factorial(7)
  coef8 = h*(h^6-21*h^4+105*h^2-105)*k*(k^6-21*k^4+105*k^2-105)/factorial(8)
  serie1 <- function(x){
    return(-1*eps+coef1*x+coef2*x^2+coef3*x^3+coef4*x^4+coef5*x^5+coef6*x^6+coef7*x^7+coef8*x^8)
  }
  r1 <-  uniroot.all(serie1, c(-1,1))
  serie2 <- function(x){
    return(-1*eps+ x + h*k/2*x^2-(h^2+k^2-(h^2)*(k^2))/6*x^3 + h*k*((h^2)*(k^2)-3*(h^2+k^2)+5)/24*x^4)
  }
  tet <-  uniroot.all(serie2, c(-1,1))
  r2 <- sin(tet)
  per <- function (r){
    beta1 <- (h-r*k)/sqrt(1-r^2)
    beta2 <- (k-r*h)/sqrt(1-r^2)
    psi1 <- pnorm(beta1)-0.5
    psi2 <- pnorm(beta2)-0.5
    chi0 <- (1/(2*pi))*(1/sqrt(1-r^2))*exp(-0.5*(1/(1-r^2))*(h^2+k^2-2*r*h*k))
    return(qnorm(3/4)/(sqrt(N)*chi0*N)*sqrt(((a+d)*(c+b))/(4)+psi2^2*((a+c)*(b+d))+psi1^2*((a+b)*(c+d))+2*psi1*psi2*(a*d-b*c)-psi2*(a*b-c*d)-psi1*(a*c-b*d)))
  }
  if(length(r1)==1 & length(r2)==1){
    x <- data.frame(Estimacion = c(r1,r2,h,k),
                    P.E. = c(per(r1),per(r2),peh,pek),
                    l.lim = c(r1-per(r1),r2-per(r2),h-peh,k-pek),
                    u.lim = c(r1+per(r1),r2+per(r2),h+peh,k+pek),
                    row.names = c("Coef. Corr. 1","Coef. Corr. 2","h","k"))
    
    return(x)
  }
  if(length(r1)==1 & length(r2)!=1){
    x <- data.frame(Estimacion = c(r1,h,k),
                    P.E. = c(per(r1),peh,pek),
                    l.lim = c(r1-per(r1),h-peh,k-pek),
                    u.lim = c(r1+per(r1),h+peh,k+pek),
                    row.names = c("Coef. Corr. 1","h","k"))
    
    return(list(x, "La serie 2 obtiene los siguientes valores:",r2))
  }
  if(length(r1)!=1 & length(r2)==1){
    x <- data.frame(Estimacion = c(r2,h,k),
                    P.E. = c(per(r2),peh,pek),
                    l.lim = c(r2-per(r2),h-peh,k-pek),
                    u.lim = c(r2+per(r2),h+peh,k+pek),
                    row.names = c("Coef. Corr. 2","h","k"))
    
    return(list(x, "La serie 1 obtiene los siguientes valores:",r1))
  }
  if(length(r1)==0 & length(r2)==0){
    return("No se pudo calcular.")
  }
  else{
    return(list("La serie 1 obtiene:",r1,"La serie 2 obtiene:",r2))
  }
}

```

La función de la tablita de frecuencias simuladas:

```{r,echo=TRUE,eval=TRUE,attr.source='.numberLines'}
frecuencias <- function(N,sigma1,sigma2,rhot,h,k){
  z <- function(x,y){
    N/(2*pi*sigma1*sigma2*sqrt(1-rhot^2))*exp(-0.5*(1/(1-rhot^2))*((x/sigma1)^2+(y/sigma2)^2-2*rhot*x*y/(sigma1*sigma2)))
  }
  aux1 <- pbivnorm::pbivnorm(x=c(h/s1), y=c(k/s2), rho=p)
  a <- N*aux1
  aux2 <- pbivnorm::pbivnorm(x=c(Inf), y=c(k/s2), rho=p)
  b <- N*(aux2-aux1)
  aux3 <- pbivnorm::pbivnorm(x=c(h/s1), y=c(Inf), rho=p)
  c <- N*(aux3-aux1)
  d <- N*(1-aux2-aux3+aux1)
  return(c(round(a),round(b),round(c),round(d)))
}

```

Aplicando mi función a las ilustraciones de Pearson:

```{r, echo=TRUE, eval=TRUE,attr.source='.numberLines'}
library(psych)
library(pbivnorm)
library(rootSolve)

#Ilustración 1 de Pearson
rhot(631,125,147,147) #mi función
(tetrachoric(matrix(c(631,125,147,147),2,2)))  #función de la librería psych
#Ilustración 3 de Pearson
rhot(1766,842,842,722)
(tetrachoric(matrix(c(1766,842,842,722),2,2)))  #función de la librería psych
#Ilustración 6 de Pearson
rhot(1562,42,383,94)
(tetrachoric(matrix(c(1562,42,383,94),2,2)))  #función de la librería psych
```

Ejemplo simulados

```{r, echo=TRUE,eval=TRUE,attr.output = ".numberLines"}
#Ejemplo 1
N <- 1000
s1 <- 5
s2 <- 5
p <- 0.4
h <- 4
k <- 1
ns <- frecuencias(N,s1,s2,p,h,k)
ns
sum(ns)
rhot(ns[1],ns[2],ns[3],ns[4]) #Mi función
(tetrachoric(matrix(c(ns[1],ns[2],ns[3],ns[4]),2,2))) #Función de la librería psych

#Ejemplo 4, NO se rechaza que p=0 porque N es pequeña
N <- 1000
s1 <- 5
s2 <- 5
p <- 0.05
h <- 4
k <- 1
ns <- frecuencias(N,s1,s2,p,h,k)
ns
sum(ns)
rhot(ns[1],ns[2],ns[3],ns[4]) #Mi función
(tetrachoric(matrix(c(ns[1],ns[2],ns[3],ns[4]),2,2))) #Función de la librería psych

#Ejemplo 7 ejemplo loco
N <- 1000
s1 <- 1
s2 <- 1
p <- -0.89
h <- 15 #vs 3
k <- 0.3
ns <- frecuencias(N,s1,s2,p,h,k)
ns
sum(ns)
rhot(ns[1],ns[2],ns[3],ns[4]) #Mi función
(tetrachoric(matrix(c(ns[1],ns[2],ns[3],ns[4]),2,2))) #Función de la librería psych

#Ejemplo 8 ejemplo loco
N <- 1000
s1 <- 1
s2 <- 1
p <- -0.89
h <- 3 #vs15
k <- 0.3
ns <- frecuencias(N,s1,s2,p,h,k)
ns
sum(ns)
rhot(ns[1],ns[2],ns[3],ns[4]) #Mi función
(tetrachoric(matrix(c(ns[1],ns[2],ns[3],ns[4]),2,2))) #Función de la librería psych

#Ejemplo 9 ejemplo loco
N <- 1000
s1 <- 1
s2 <- 1
p <- -0.89
h <- 0.1 #vs15
k <- 0.3
ns <- frecuencias(N,s1,s2,p,h,k)
ns
sum(ns)
rhot(ns[1],ns[2],ns[3],ns[4]) #Mi función
(tetrachoric(matrix(c(ns[1],ns[2],ns[3],ns[4]),2,2))) #Función de la librería psych


```







